server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ktorm-ksp-springboot-demo
    username: root
    password:

jwt:
  header: "Authorization"
  tokenHead: "Bearer "
  secret: GoodMorning